name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install AWS CLI
        run: |
          sudo apt-get install python3-pip
          pip3 install awscli --upgrade --user

      - name: Deploy to AWS
        run: |
          aws configure set aws_access_key_id ${{ var.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ var.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ var.AWS_REGION }}
